#PBS -N AMM7
#PBS -l select=21
#PBS -l walltime=00:20:00
#PBS -A n01-CLASS

## PBS_O_WORKDIR = directory from which the batch job is launched.
echo "PBS_O_WORKDIR = " $PBS_O_WORKDIR
cd $PBS_O_WORKDIR
export NPROC=`qstat -f $PBS_JOBID | grep mppwidth | awk '{print $3}'`
echo "Running on $NPROC cores"

OCEANCORES=143
XIOCORES=1

export OMP_NUM_THREADS=1

ulimit -c unlimited
ulimit -s unlimited

date


# Copy correct namelist template into position


for year in {2005..2005}
do

# Array pretending to be a Pythonic dictionary
ARRAY=( "sf_L51_r05:51"
        "sf_L51_r10:51"
        "sf_L51_r24:51"   )

for ens in "${ARRAY[@]}"
do

  rdt=300
  bar=30
  nam="${ens%%:*}"
  jpk="${ens##*:}"

  if [ $year -eq 2005 ]
  then
    tst=1
    rst=".false."
  else
    tst=`./end_time_step $(( $year - 1 )) $rdt` ; rs0=`printf "%08d" $tst`; tst=$(( $tst +1 ))
    rst=".true."
  fi
  ten=`./end_time_step $year $rdt`
  ten=15
  sed "s/__EXP__/$nam/g" ../ENSEMBLE_CONTROL/namelist.template.hpg > tmp_out ; mv tmp_out namelist
  sed "s/__TST__/$tst/g"                    namelist               > tmp_out ; mv tmp_out namelist
  sed "s/__RS0__/restart_$nam\_$rs0/g"      namelist               > tmp_out ; mv tmp_out namelist
  sed "s/__YRS__/$year/g"                   namelist               > tmp_out ; mv tmp_out namelist
  sed "s/__TEN__/$ten/g"                    namelist               > tmp_out ; mv tmp_out namelist
  sed "s/__RDT__/$rdt/g"                    namelist               > tmp_out ; mv tmp_out namelist
  sed "s/__BAR__/$bar/g"                    namelist               > tmp_out ; mv tmp_out namelist
  sed "s/__RST__/$rst/g"                    namelist               > tmp_out ; mv tmp_out ../ENSEMBLE_MEMBERS/$nam/namelist_cfg
  rm namelist

done

for ens in "${ARRAY[@]}"
do
  xp="${ens%%:*}"
  cd $PBS_O_WORKDIR/../ENSEMBLE_MEMBERS/$xp
  pwd
  echo "aprun -b -n $XIOCORES -N 1 ./xios_server.exe : -n $OCEANCORES -N 24 ./nemo &"
  cp namelist_cfg meta_out/namelist.$year
  aprun -b -n $OCEANCORES -N 24 ./nemo   >&  stdouterr_nemo : -n $XIOCORES -N 1 ./xios_server.exe >&  stdouterr_xios &
  echo $xp
  date
done

wait
date

cd $PBS_O_WORKDIR
for ens in "${ARRAY[@]}"
do
  xp="${ens%%:*}"
  cd $PBS_O_WORKDIR/../ENSEMBLE_MEMBERS/$xp
  mv *_1?_*grid*.nc OUTPUTS &
  echo $xp
  date

done
wait

cd $PBS_O_WORKDIR
done

exit
