#!/bin/bash
# Lightweight script to set up AMM7 on CIRRUS
 
display_usage() { 
   echo
   echo "  Auto-Config: AMM7 on ARCHER"
   echo "  ***************************************"
   echo
   echo "  usage: ${0##*/} -w path_to_install_nemo -x path_to_intall_xios -s path_to_repo"
   echo
   echo "  flags:  -w full path to where nemo will be installed"
   echo "          -x full path to where xios will be installed"
   echo "          -s full path to where AMM7 repository resides"
   echo
   exit 1
	} 
# if less than three arguments supplied, display usage 
	if [  $# -le 5 ] 
	then 
		display_usage
		exit 1
	fi 
# if less than two arguments supplied, display usage 
	if [  $# -ge 7 ] 
	then 
		display_usage
		exit 1
	fi 
# check whether user had supplied -h or --help . If yes display usage 
	if [[ ( $# == "--help") ||  $# == "-h" ]] 
	then 
		display_usage
		exit 0
	fi 

while getopts w:x:s: option
  do
  case "${option}"
  in
  w) export WORK_DIR=${OPTARG};;
  x) export XIOS_DIR=${OPTARG};;
  s) export REPO_DIR=${OPTARG};;
  esac
done

if [ ${WORK_DIR:0:1} != "/" ]; then
  echo "WORK_DIR must use full path"
  exit 1
fi

if [ ${XIOS_DIR:0:1} != "/" ]; then
  echo "XIOS_DIR must use full path"
  exit 1
fi

if [ ${REPO_DIR:0:1} != "/" ]; then
  echo "REPO_DIR must use full path"
  exit 1
fi

# Change to some working directory of choice
if [ ! -d "$WORK_DIR" ]; then
  mkdir $WORK_DIR
fi
cd $WORK_DIR

echo "Making sure that the correct modules are loaded"

module swap PrgEnv-cray PrgEnv-intel
module load cray-hdf5-parallel
module load cray-netcdf-hdf5parallel

# Checkout the NEMO code from the SVN Paris repository 
echo "Checking out NEMO repository"
svn co http://forge.ipsl.jussieu.fr/nemo/svn/NEMO/releases/release-3.6/NEMOGCM nemo

# Setup the directory structure for the ENSEMBLE
mkdir $WORK_DIR/nemo/CONFIG/AMM7
# Define the location of where the AMM7 forcing files are to be downloaded 
export DOWNLOAD_DIR="$WORK_DIR/nemo/CONFIG/AMM7/EXP00/"

echo $XIOS_DIR
# Choose an appropriate directory for your XIOS installation
if [ ! -d "$XIOS_DIR" ]; then
  mkdir $XIOS_DIR
fi
cd $XIOS_DIR
echo $PWD
echo "Checking out xios repository"
svn co http://forge.ipsl.jussieu.fr/ioserver/svn/XIOS/branchs/xios-1.0@703 xios 
cd xios
cp $REPO_DIR/arch/xios/* ./arch
echo "Compiling xios"
./make_xios --full --prod --arch archer --netcdf_lib netcdf4_par --job 4

# Let's update the path to xios
export XIOS_DIR=$XIOS_DIR/xios

cd $WORK_DIR/nemo
cp $REPO_DIR/arch/nemo/* ./ARCH

echo 'AMM7 OPA_SRC' >> $WORK_DIR/nemo/CONFIG/cfg.txt

mkdir CONFIG/AMM7/EXP00
echo "Gathering forcing data"

export CONFIG_DIR=$WORK_DIR/nemo/CONFIG/AMM7

# Set up EXP00 for quick testing of the unforced case

cd $CONFIG_DIR/EXP00
ln -s ../../SHARED/namelist_ref namelist_ref
ln -s ../../SHARED/field_def.xml field_def.xml
ln -s ../../SHARED/domain_def.xml domain_def.xml
wget http://gws-access.ceda.ac.uk/public/jmmp_colab/AMM7/cfgs/domain_cfg.nc


ln -s $XIOS_DIR/bin/xios_server.exe $CONFIG_DIR/EXP00/xios_server.exe

cp $REPO_DIR/EXP00/* $CONFIG_DIR/EXP00/
cp -r $REPO_DIR/MY_SRC $CONFIG_DIR
cp $REPO_DIR/cpp_AMM7.fcm $CONFIG_DIR/

cd $WORK_DIR/nemo/CONFIG

echo "Compiling nemo AMM7 Config"
./makenemo -m archer -n AMM7 -j 8

echo
echo "  Auto-Config: AMM7"
echo "  *****************************"
echo
echo "  To run the AMM7 Configuration:"
echo
echo "  - update the runscript.pbs accordingly "
echo "      (project code, nodes, modules, etc)"
echo
echo "  - submit via the qsub command"
echo    
