#!/bin/bash
# Lightweight script to set up AMM7 on ARCHER2 
 
display_usage() { 
   echo
   echo "  Auto-Config: AMM7 on ARCHER2"
   echo "  ***************************************"
   echo
   echo "  usage: ${0##*/} -w path_to_install_nemo -s path_to_repo"
   echo
   echo "  flags:  -w full path to where nemo will be installed"
   echo "          -s full path to where AMM7 repository resides"
   echo
   exit 1
	} 
# if less than two arguments supplied, display usage 
	if [  $# -ge 7 ] 
	then 
		display_usage
		exit 1
	fi 
# check whether user had supplied -h or --help . If yes display usage 
	if [[ ( $# == "--help") ||  $# == "-h" ]] 
	then 
		display_usage
		exit 0
	fi 

while getopts w:s: option
  do
  case "${option}"
  in
  w) export WORK_DIR=${OPTARG};;
  s) export REPO_DIR=${OPTARG};;
  esac
done

if [ ${WORK_DIR:0:1} != "/" ]; then
  echo "WORK_DIR must use full path"
  exit 1
fi

if [ ${REPO_DIR:0:1} != "/" ]; then
  echo "REPO_DIR must use full path"
  exit 1
fi

# Change to some working directory of choice
if [ ! -d "$WORK_DIR" ]; then
  mkdir $WORK_DIR
fi
cd $WORK_DIR


# Checkout the NEMO code from the SVN Paris repository 
echo "Checking out NEMO repository"
git clone --branch 4.2.1 https://forge.nemo-ocean.eu/nemo/nemo.git nemo_4.2.1

mkdir $WORK_DIR/nemo/cfgs/AMM7

cd $WORK_DIR/nemo_4.2.1

echo 'AMM7 OCE' >> $WORK_DIR/nemo_4.2.1/cfgs/work_cfgs.txt

mkdir cfgs/AMM7/EXP00
mkdir cfgs/AMM7/EXP_REF

export CONFIG_DIR=$WORK_DIR/nemo_4.2.1/cfgs/AMM7

cd $CONFIG_DIR/EXP_REF
ln -s ../../SHARED/namelist_ref namelist_ref
ln -s ../../SHARED/grid_def_nemo.xml grid_def_nemo.xml
ln -s ../../SHARED/domain_def_nemo.xml domain_def_nemo.xml

cp $REPO_DIR/EXP/* $CONFIG_DIR/EXP_REF/.
cp -r $REPO_DIR/MY_SRC $CONFIG_DIR/.
cp $REPO_DIR/cpp_AMM7.fcm $CONFIG_DIR/.

cd $CONFIG_DIR
mkdir INPUTS
cd INPUTS
mkdir BDY
mkdir TIDE
mkdir SBC
mkdir RIV
mkdir DOM
mkdir IC
cd BDY
mkdir COORD
mkdir OPEN
mkdir SKAG
cd $WORK_DIR/nemo_4.2.1
